const mongoose = require("mongoose")

const fbPlayerFantasyPointsSchema = mongoose.Schema({
    "season_id": { type: Number },
    "league_id": { type: Number },
    "match_id": { type: Number },
    "team_id": { type: Number },
    "pid": { type: Number },
    "tp": { type: Number, default: 0 },
    "goalfor": { type: Number, default: 0 },
    "goalmid": { type: Number, default: 0 },
    "goalgk": { type: Number, default: 0 },
    "goaldef": { type: Number, default: 0 },
    "cleansheetmid": { type: Number, default: 0 },
    "cleansheetgk": { type: Number, default: 0 },
    "cleansheetdef": { type: Number, default: 0 },
    "penaltysavegk": { type: Number, default: 0 },
    "yellowcardgk": { type: Number, default: 0 },
    "yellowcardfwd": { type: Number, default: 0 },
    "yellowcardmid": { type: Number, default: 0 },
    "yellowcarddef": { type: Number, default: 0 },
    "redcardgk": { type: Number, default: 0 },
    "redcardfwd": { type: Number, default: 0 },
    "redcardmid": { type: Number, default: 0 },
    "redcarddef": { type: Number, default: 0 },
    "owngoalgk": { type: Number, default: 0 },
    "owngoalfwd": { type: Number, default: 0 },
    "owngoalmid": { type: Number, default: 0 },
    "owngoaldef": { type: Number, default: 0 },
    "goalsconcededgk": { type: Number, default: 0 },
    "penaltymissedgk": { type: Number, default: 0 },
    "penaltymissedfwd": { type: Number, default: 0 },
    "penaltymissedmid": { type: Number, default: 0 },
    "penaltymisseddef": { type: Number, default: 0 },
    "tacklefwd": { type: Number, default: 0 },
    "tacklemid": { type: Number, default: 0 },
    "tackledef": { type: Number, default: 0 },
    "fourpassesgk": { type: Number, default: 0 },
    "fourpassesfwd": { type: Number, default: 0 },
    "fourpassesmid": { type: Number, default: 0 },
    "fourpassesdef": { type: Number, default: 0 },
    "goalsaved": { type: Number, default: 0 },
    "goalsconcededdef": { type: Number, default: 0 },
    "goalsconcededmid": { type: Number, default: 0 },
    "goalsconcededfow": { type: Number, default: 0 },
    "penaltyscoredgk": { type: Number, default: 0 },
    "penaltyscoredfor": { type: Number, default: 0 },
    "penaltyscoredmid": { type: Number, default: 0 },
    "penaltyscoreddef": { type: Number, default: 0 },
    "foulsdrawnfwd": { type: Number, default: 0 },
    "foulsdrawnmid": { type: Number, default: 0 },
    "foulsdrawndef": { type: Number, default: 0 },
    "interceptionsfwd": { type: Number, default: 0 },
    "interceptionsmid": { type: Number, default: 0 },
    "interceptionsdef": { type: Number, default: 0 },
    "duelswonfwd": { type: Number, default: 0 },
    "duelswonmid": { type: Number, default: 0 },
    "duelswondef": { type: Number, default: 0 },
    "punches": { type: Number, default: 0 },
    "shot_off_targetfwd": { type: Number, default: 0 },
    "shot_off_targetmid": { type: Number, default: 0 },
    "shot_off_targetdef": { type: Number, default: 0 },
    "chancecreatedfwd": { type: Number, default: 0 },
    "chancecreatedmid": { type: Number, default: 0 },
    "chancecreateddef": { type: Number, default: 0 },
    "threemispassgk": { type: Number, default: 0 },
    "threemispassfwd": { type: Number, default: 0 },
    "threemispassmid": { type: Number, default: 0 },
    "threemispassdef": { type: Number, default: 0 },
    "playing11": { type: Number, default: 0 },
    "threegoalfwd": { type: Number, default: 0 },
    "threegoalmid": { type: Number, default: 0 },
    "threegoaldef": { type: Number, default: 0 },
    "twogoalfwd": { type: Number, default: 0 },
    "twogoalmid": { type: Number, default: 0 },
    "twogoaldef": { type: Number, default: 0 },
    "shot_on_targetfwd": { type: Number, default: 0 },
    "shot_on_targetmid": { type: Number, default: 0 },
    "shot_on_targetdef": { type: Number, default: 0 },
    "foul_concededgk": { type: Number, default: 0 },
    "foul_concededfor": { type: Number, default: 0 },
    "foul_concededmid": { type: Number, default: 0 },
    "foul_concededdef": { type: Number, default: 0 },
    "dribbles_completedfwd": { type: Number, default: 0 },
    "dribbles_completedmid": { type: Number, default: 0 },
    "dribbles_completeddef": { type: Number, default: 0 },
    "assistfow": { type: Number, default: 0 },
    "assistmid": { type: Number, default: 0 },
    "assistdef": { type: Number, default: 0 },
    "assistgk": { type: Number, default: 0 },
    "playsixtymingk": { type: Number, default: 0 },
    "playsixtyminfwd": { type: Number, default: 0 },
    "playsixtyminmid": { type: Number, default: 0 },
    "playsixtymindef": { type: Number, default: 0 },
    "cleansheetfwd": { type: Number, default: 0 },
    //////////NEW/////////////
    "shots_off_target_gk": { type: Number, default: 0 },
    "shots_blocked_gk": { type: Number, default: 0 },
    "long_passes_gk": { type: Number, default: 0 },
    "short_passes_gk": { type: Number, default: 0 },
    "challenges_gk": { type: Number, default: 0 },
    "yellowcards_gk": { type: Number, default: 0 },
    "clearances_gk": { type: Number, default: 0 },
    "saves_inside_box_gk": { type: Number, default: 0 },
    "dribbled_past_gk": { type: Number, default: 0 },
    "penalties_saved_gk": { type: Number, default: 0 },
    "rating_gk": { type: Number, default: 0 },
    "long_balls_gk": { type: Number, default: 0 },
    "long_balls_won_gk": { type: Number, default: 0 },
    "matches_gk": { type: Number, default: 0 },
    "appearances_gk": { type: Number, default: 0 },
    "bench_gk": { type: Number, default: 0 },
    "error_lead_to_goal_gk": { type: Number, default: 0 },
    "shots_off_target_def": { type: Number, default: 0 },
    "offsides_def": { type: Number, default: 0 },
    "shots_blocked_def": { type: Number, default: 0 },
    "long_passes_def": { type: Number, default: 0 },
    "short_passes_def": { type: Number, default: 0 },
    "hit_woodwork_def": { type: Number, default: 0 },
    "successful_headers_def": { type: Number, default: 0 },
    "headers_def": { type: Number, default: 0 },
    "challenges_def": { type: Number, default: 0 },
    "yellowcards_def": { type: Number, default: 0 },
    "dispossessed_def": { type: Number, default: 0 },
    "offsides_provoked_def": { type: Number, default: 0 },
    "total_crosses_def": { type: Number, default: 0 },
    "accurate_crosses_def": { type: Number, default: 0 },
    "clearances_def": { type: Number, default: 0 },
    "total_duels_def": { type: Number, default: 0 },
    "aerials_won_def": { type: Number, default: 0 },
    "dribbled_past_def": { type: Number, default: 0 },
    "penalties_won_def": { type: Number, default: 0 },
    "rating_def": { type: Number, default: 0 },
    "long_balls_def": { type: Number, default: 0 },
    "long_balls_won_def": { type: Number, default: 0 },
    "through_balls_def": { type: Number, default: 0 },
    "through_balls_won_def": { type: Number, default: 0 },
    "matches_def": { type: Number, default: 0 },
    "appearances_def": { type: Number, default: 0 },
    "bench_def": { type: Number, default: 0 },
    "error_lead_to_goal_def": { type: Number, default: 0 },
    "shots_off_target_mid": { type: Number, default: 0 },
    "offsides_mid": { type: Number, default: 0 },
    "shots_blocked_mid": { type: Number, default: 0 },
    "long_passes_mid": { type: Number, default: 0 },
    "short_passes_mid": { type: Number, default: 0 },
    "hit_woodwork_mid": { type: Number, default: 0 },
    "successful_headers_mid": { type: Number, default: 0 },
    "headers_mid": { type: Number, default: 0 },
    "challenges_mid": { type: Number, default: 0 },
    "yellowcards_mid": { type: Number, default: 0 },
    "dispossessed_mid": { type: Number, default: 0 },
    "offsides_provoked_mid": { type: Number, default: 0 },
    "total_crosses_mid": { type: Number, default: 0 },
    "accurate_crosses_mid": { type: Number, default: 0 },
    "clearances_mid": { type: Number, default: 0 },
    "total_duels_mid": { type: Number, default: 0 },
    "aerials_won_mid": { type: Number, default: 0 },
    "dribbled_past_mid": { type: Number, default: 0 },
    "penalties_won_mid": { type: Number, default: 0 },
    "rating_mid": { type: Number, default: 0 },
    "long_balls_mid": { type: Number, default: 0 },
    "long_balls_won_mid": { type: Number, default: 0 },
    "through_balls_mid": { type: Number, default: 0 },
    "through_balls_won_mid": { type: Number, default: 0 },
    "matches_mid": { type: Number, default: 0 },
    "appearances_mid": { type: Number, default: 0 },
    "bench_mid": { type: Number, default: 0 },
    "error_lead_to_goal_mid": { type: Number, default: 0 },
    "shots_off_target_fwd": { type: Number, default: 0 },
    "offsides_fwd": { type: Number, default: 0 },
    "shots_blocked_fwd": { type: Number, default: 0 },
    "long_passes_fwd": { type: Number, default: 0 },
    "short_passes_fwd": { type: Number, default: 0 },
    "hit_woodwork_fwd": { type: Number, default: 0 },
    "successful_headers_fwd": { type: Number, default: 0 },
    "headers_fwd": { type: Number, default: 0 },
    "challenges_fwd": { type: Number, default: 0 },
    "yellowcards_fwd": { type: Number, default: 0 },
    "dispossessed_fwd": { type: Number, default: 0 },
    "total_crosses_fwd": { type: Number, default: 0 },
    "accurate_crosses_fwd": { type: Number, default: 0 },
    "clearances_fwd": { type: Number, default: 0 },
    "total_duels_fwd": { type: Number, default: 0 },
    "aerials_won_fwd": { type: Number, default: 0 },
    "dribbled_past_fwd": { type: Number, default: 0 },
    "penalties_won_fwd": { type: Number, default: 0 },
    "rating_fwd": { type: Number, default: 0 },
    "long_balls_fwd": { type: Number, default: 0 },
    "long_balls_won_fwd": { type: Number, default: 0 },
    "through_balls_fwd": { type: Number, default: 0 },
    "through_balls_won_fwd": { type: Number, default: 0 },
    "matches_fwd": { type: Number, default: 0 },
    "appearances_fwd": { type: Number, default: 0 },
    "bench_fwd": { type: Number, default: 0 },
    "error_lead_to_goal_fwd": { type: Number, default: 0 }
    
},
    {
        timestamps: true,
        versionKey: false,
        toJSON: { virtuals: true }, // Include virtuals in JSON responses
        toObject: { virtuals: true }, // Include virtuals in object responses
    });

// Add a virtual field for `id`
fbPlayerFantasyPointsSchema.virtual("id").get(function () {
    return this._id.toHexString(); // Convert _id (ObjectId) to a string
});

const createFbPlayerFantasyPointsModel = (connection) => {
    return connection.model("fb_player_fantasy_points", fbPlayerFantasyPointsSchema);
};

module.exports = createFbPlayerFantasyPointsModel;
