const mongoose = require("mongoose")

const footballPlayersFantasySchema = mongoose.Schema({
    "season_id": { type: Number },
    "league_id": { type: Number },
    "match_id": { type: Number },
    "team_id": { type: Number },
    "pid": { type: Number },
    "playing11": { type: Number, default: 0 },
    "goal": { type: Number, default: 0 },
    "penaltysave": { type: Number, default: 0 },
    "threegoalsaved": { type: Number, default: 0 },
    "goalsconcededgk": { type: Number, default: 0 },
    "goalsconcededdef": { type: Number, default: 0 },
    "goalsconcededmid": { type: Number, default: 0 },
    "goalsconcededfow": { type: Number, default: 0 },
    "assistfow": { type: Number, default: 0 },
    "assistmid": { type: Number, default: 0 },
    "assistdef": { type: Number, default: 0 },
    "assistgk": { type: Number, default: 0 },
    "redcard": { type: Number, default: 0 },
    "yellowcard": { type: Number, default: 0 },
    "penaltymissed": { type: Number, default: 0 },
    "tenpasses": { type: Number, default: 0 },
    "twoshottarget": { type: Number, default: 0 },
    "tp": { type: Number, default: 0 },
    "penaltyscored": { type: Number, default: 0 },
    "aerials_won": { type: Number, default: 0 },
    "punches": { type: Number, default: 0 },
    "chancecreated": { type: Number, default: 0 },
    "twogoal": { type: Number, default: 0 },
    "foul_concededgk": { type: Number, default: 0 },
    "foul_concededfor": { type: Number, default: 0 },
    "foul_concededmid": { type: Number, default: 0 },
    "foul_concededdef": { type: Number, default: 0 },
    "goalsaved": { type: Number, default: 0 },
    "penaltyscoredgk": { type: Number, default: 0 },
    "penaltyscoredfor": { type: Number, default: 0 },
    "penaltyscoredmid": { type: Number, default: 0 },
    "penaltyscoreddef": { type: Number, default: 0 },
    "penaltymissedgk": { type: Number, default: 0 },
    "penaltymissedfwd": { type: Number, default: 0 },
    "penaltymissedmid": { type: Number, default: 0 },
    "penaltymisseddef": { type: Number, default: 0 },
    "dribbles_completedfwd": { type: Number, default: 0 },
    "dribbles_completedmid": { type: Number, default: 0 },
    "dribbles_completeddef": { type: Number, default: 0 },
    "duelswonfwd": { type: Number, default: 0 },
    "duelswonmid": { type: Number, default: 0 },
    "duelswondef": { type: Number, default: 0 },
    "owngoalgk": { type: Number, default: 0 },
    "owngoalfwd": { type: Number, default: 0 },
    "owngoalmid": { type: Number, default: 0 },
    "owngoaldef": { type: Number, default: 0 },
    "redcardgk": { type: Number, default: 0 },
    "redcardfwd": { type: Number, default: 0 },
    "redcardmid": { type: Number, default: 0 },
    "redcarddef": { type: Number, default: 0 },
    "yellowcardgk": { type: Number, default: 0 },
    "yellowcardfwd": { type: Number, default: 0 },
    "yellowcardmid": { type: Number, default: 0 },
    "yellowcarddef": { type: Number, default: 0 },
    "cleansheetgk": { type: Number, default: 0 },
    "cleansheetfwd": { type: Number, default: 0 },
    "cleansheetmid": { type: Number, default: 0 },
    "cleansheetdef": { type: Number, default: 0 },
    "interceptionsfwd": { type: Number, default: 0 },
    "interceptionsmid": { type: Number, default: 0 },
    "interceptionsdef": { type: Number, default: 0 },
    "tacklefwd": { type: Number, default: 0 },
    "tacklemid": { type: Number, default: 0 },
    "tackledef": { type: Number, default: 0 },
    "threemispassgk": { type: Number, default: 0 },
    "threemispassfwd": { type: Number, default: 0 },
    "threemispassmid": { type: Number, default: 0 },
    "threemispassdef": { type: Number, default: 0 },
    "foulsdrawngk": { type: Number, default: 0 },
    "foulsdrawnfwd": { type: Number, default: 0 },
    "foulsdrawnmid": { type: Number, default: 0 },
    "foulsdrawndef": { type: Number, default: 0 },
    "twogoalfwd": { type: Number, default: 0 },
    "twogoalmid": { type: Number, default: 0 },
    "twogoaldef": { type: Number, default: 0 },
    "threegoalfwd": { type: Number, default: 0 },
    "threegoalmid": { type: Number, default: 0 },
    "threegoaldef": { type: Number, default: 0 },
    "shot_off_targetfwd": { type: Number, default: 0 },
    "shot_off_targetmid": { type: Number, default: 0 },
    "shot_off_targetdef": { type: Number, default: 0 },
    "shot_on_targetfwd": { type: Number, default: 0 },
    "shot_on_targetmid": { type: Number, default: 0 },
    "shot_on_targetdef": { type: Number, default: 0 },
    "tenpassesgk": { type: Number, default: 0 },
    "tenpassesfwd": { type: Number, default: 0 },
    "tenpassesmid": { type: Number, default: 0 },
    "tenpassesdef": { type: Number, default: 0 },
    "playsixtymingk": { type: Number, default: 0 },
    "playsixtyminfwd": { type: Number, default: 0 },
    "playsixtyminmid": { type: Number, default: 0 },
    "playsixtymindef": { type: Number, default: 0 },
    "chancecreatedfwd": { type: Number, default: 0 },
    "chancecreatedmid": { type: Number, default: 0 },
    "chancecreateddef": { type: Number, default: 0 },
    "fourpassesgk": { type: Number, default: 0 },
    "fourpassesfwd": { type: Number, default: 0 },
    "fourpassesmid": { type: Number, default: 0 },
    "fourpassesdef": { type: Number, default: 0 },
    "goalfor": { type: Number, default: 0 },
    "goalmid": { type: Number, default: 0 },
    "goalgk": { type: Number, default: 0 },
    "goaldef": { type: Number, default: 0 },
},
    {
        timestamps: true,
        versionKey: false
    })

module.exports = mongoose.model("fbplyrfantpoints", footballPlayersFantasySchema)